class Exception
{
public static void main(String[] args)
{
try
{
System.out.println(10/0);
}
catch
(
System.out.println("infinit value");
)
}
}